from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from backend.app.core.database import get_db
from backend.app.models.entities import create_audit_log
from backend.app.schemas.domain import QueryRequest, QueryResponse
from backend.app.services.rag_service import rag_service

router = APIRouter(prefix="/query", tags=["RAG Query"])

@router.post("", response_model=QueryResponse)
def query_rag(req: QueryRequest, db: Session = Depends(get_db)):
    system_id = req.system_id or "SYS-MES-001"
    mode = req.mode or "General Q&A"
    result = rag_service.query(
        question=req.question,
        system_id=system_id,
        top_k=req.top_k,
        mode=mode
    )
    
    # Add structured high-level agent execution milestones
    # The agent execution is now deterministically generated by the RAG Service pipeline.
    # No more static string simulations here.
    
    # Audit log query event
    create_audit_log(
        db=db,
        actor_type="USER",
        actor_id="qa@demo.local",
        action="RAG_QUERY",
        entity_type="QUERY",
        entity_id=system_id,
        details={
            "question": req.question,
            "mode": mode,
            "confidence": result.confidence,
            "citations_count": len(result.citations),
            "sources_count": len(result.sources),
            "warnings": result.warnings
        },
        agent_name="supervisor_agent"
    )
    
    return result
